### ISSUE TITLE
Formular to do:

### ISSUE THREAD

**Issue by AlinGpro** [ProRO/Pro-Ro---Part-1#30]
1. recreat nume imagine
2. verificat cand userul e logat sau nu
3. pop-up login/register
4. logare automata dupa inregistrate
5. sa verifice daca s-au uploadat imagini
6. salvare cerere cu titlu generat automat. Format: serviciu, strada, oras, sector
7. youtube google maps

**Comment by ioanbogdanpopa** [comment]
3. de modificat scos pop-up login daca nu exista token. De verificat doar dupa continue cu user invalid
7. Implementat google maps
6. dupa google maps
